# Generated by Django 3.1.4 on 2020-12-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='detail',
            field=models.CharField(max_length=400),
        ),
    ]
