# Generated by Django 3.1.4 on 2021-01-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': 'Ratings'},
        ),
    ]
