# Generated by Django 3.1.4 on 2021-01-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20201213_1544'),
        ('comments', '0005_auto_20210103_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='snippet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.snippet'),
        ),
    ]
