# Generated by Django 3.1.4 on 2020-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description_html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='highlighted_code',
            field=models.TextField(),
        ),
    ]
