# Generated by Django 3.1.4 on 2020-12-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='snippet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.snippet'),
        ),
    ]
