# Generated by Django 3.1.4 on 2021-01-17 09:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20201213_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
