# Generated by Django 3.1.4 on 2021-01-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20210117_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description_html',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='highlighted_code',
            field=models.TextField(editable=False),
        ),
    ]
